apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s5nbih2fa-python 
  janus-idp.io/tekton: s5nbih2fa-python
  backstage.io/kubernetes-id: s5nbih2fa-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s5nbih2fa-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml