apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s5nbih2fa-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s5nbih2fa-python 
  name: s5nbih2fa-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: s5nbih2fa-python 
